baseURL = "https://renevallecillo.github.io/GamesDemo/"
languageCode = "en-us"
title = "Games Demo"
theme = "slate"

# list of nav tags
[[ params.nav ]]
name = "Source"
tag = "source"
icon = "code"

[[ params.nav ]]
name = "Embedded"
tag = "embedded"
icon = "bookmark"
